module git_info_generator;
import std.string: format, strip;
import std.file: write;
import std.process: executeShell;

void main()
{
    string commit_hash, commit_datetime;

    if(executeShell("git status").status)
    {
        commit_hash = "not available - no git executable was found";
        commit_datetime = "not available - no git executable was found";
    }
    else
    {
        commit_hash = executeShell("git rev-parse HEAD").output.strip;
        commit_datetime = executeShell("git log -1 --format=%ci").output.strip;
    }

    string gitInfoText = format(
        "module gitinfo;\n\n"

        "// DO NOT EDIT!\n"
        "// File is generated by git_info_generator.d automatically\n"
        "// using preBuildCommands section of dub package file.\n\n"

        "immutable gitCommit = \"%s\";\n"
        "immutable gitDatetime = \"%s\";\n",
        commit_hash, commit_datetime);

    write("src//gitinfo.d", gitInfoText);
}